apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l7r5wj0j0-nodejs-gitops
  description: This is GitOps manifest for l7r5wj0j0-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=l7r5wj0j0-nodejs
    backstage.io/kubernetes-id: l7r5wj0j0-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l7r5wj0j0-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l7r5wj0j0-nodejs
